/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package red.jackf.tomlconfig;

import red.jackf.tomlconfig.annotations.Config;

public class TOMLConfig {
    /**
     * Create a new Config reader instance.
     */
    public TOMLConfig() {

    }

    public <T extends Config> T readConfig(String contents, Class<T> spec) {
        return null;
    }


}
