/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package red.jackf.tomlconfig;

public class TOMLConfig {
    public static <T> T readConfig(String contents, Class<T> spec) {
        return null;
    }
}
